platform :ios, '7.0'
pod 'Facebook-iOS-SDK', '~> 3.17.0'
pod 'MBProgressHUD', '~> 0.8'
pod 'UICKeyChainStore'
pod 'IQKeyboardManager'
pod 'libextobjc/EXTScope', '~> 0.4.1'
pod 'STAlertView'
pod 'VK-ios-sdk'
pod 'CMPopTipView', '~> 2.2.0'
pod 'FDTake'
pod 'ICETutorial', '~> 1.1.1'
